# -*- coding: utf-8 -*-
"""Task 4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NlqXVSrtZAIGLLB8RZouWtbe1_RziqAo
"""

import json
import requests
import os

DB_FILE = "cart_data.json"

# --- 1. Persistence Logic (Save/Load) ---
def load_cart():
    if os.path.exists(DB_FILE):
        with open(DB_FILE, "r") as f:
            return json.load(f)
    return {}

def save_cart(cart):
    with open(DB_FILE, "w") as f:
        json.dump(cart, f)

# --- 2. Display Products (Fetch from API) ---
def show_products():
    print("\n--- Available Products ---")
    resp = requests.get("https://fakestoreapi.com/products?limit=5").json()
    for p in resp:
        print(f"ID: {p['id']} | {p['title'][:30]}... | ${p['price']}")
    return resp

# --- Main App Logic ---
def main():
    cart = load_cart()

    while True:
        print(f"\nItems in Cart: {sum(cart.values())}")
        action = input("(V)iew Products, (C)art, (R)emove, or (Q)uit: ").lower()

        if action == 'v':
            show_products()
            pid = input("Enter Product ID to add: ")
            # 3. Add & Update Quantity
            cart[pid] = cart.get(pid, 0) + 1
            save_cart(cart)
            print("Item added!")

        elif action == 'c':
            print("\n--- Your Smart Cart ---")
            if not cart: print("Cart is empty.")
            for pid, qty in cart.items():
                print(f"Product ID: {pid} | Quantity: {qty}")

        elif action == 'r':
            pid = input("Enter Product ID to remove: ")
            # 4. Remove Item
            if pid in cart:
                del cart[pid]
                save_cart(cart)
                print("Item removed.")

        elif action == 'q':
            break

if __name__ == "__main__":
    main()

