# -*- coding: utf-8 -*-
"""Task 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zz4E0IYyYyhlBHEH_mVUvw3ICQqKbgnd
"""

import requests

def get_fakestore_data(query):
    # Simulating a search by fetching all and filtering by query
    url = "https://fakestoreapi.com/products"
    response = requests.get(url)
    if response.status_code == 200:
        products = response.json()
        # Find first product that matches the query in title
        match = next((p for p in products if query.lower() in p['title'].lower()), None)
        if match:
            return {"site": "FakeStore", "price": match['price'], "name": match['title']}
    return None

def get_dummyjson_data(query):
    url = f"https://dummyjson.com/products/search?q={query}"
    response = requests.get(url)
    if response.status_code == 200:
        data = response.json()
        if data['products']:
            match = data['products'][0]
            return {"site": "DummyJSON", "price": match['price'], "name": match['title']}
    return None

def get_platzi_data(query):
    # Using Platzi Fake Store API as the third source
    url = f"https://api.escuelajs.co/api/v1/products/?title={query}"
    response = requests.get(url)
    if response.status_code == 200:
        products = response.json()
        if products:
            match = products[0]
            return {"site": "PlatziStore", "price": match['price'], "name": match['title']}
    return None

def compare_prices(product_name):
    print(f"\nSearching for: '{product_name}'...")
    print("-" * 40)

    results = []

    # Gathering data from all 3 sources
    sources = [get_fakestore_data, get_dummyjson_data, get_platzi_data]
    for fetch_func in sources:
        res = fetch_func(product_name)
        if res:
            results.append(res)
            print(f"[{res['site']}] Found: {res['name']} | Price: ${res['price']}")

    if not results:
        print("No products found across any platforms.")
        return

    # Core Feature: Finding the Best Price
    best_deal = min(results, key=lambda x: x['price'])

    print("-" * 40)
    print(f"🌟 BEST PRICE: ${best_deal['price']}")
    print(f"📍 Available at: {best_deal['site']}")
    print("-" * 40)

if __name__ == "__main__":
    search_query = input("Enter product to search: ")
    compare_prices(search_query)

